In [7]:
import pandas as pd

In [50]:
year = 2020
month = '03'
ending = 'xlsx'
if year < 2019 and int(month) < 12:
    ending = 'xls'    
data_path = 'https://www.kba.de/SharedDocs/Publikationen/DE/Statistik/Fahrzeuge/FZ/{y}_monatlich/FZ10/fz10_{y}_{m}_{e}.{e}?__blob=publicationFile&v=2'.format(y=year,m=month,e=ending)
print(data_path)
df = pd.read_excel(data_path,sheet_name=-1,header=[7,8]).drop(df.columns[0],axis=1)

https://www.kba.de/SharedDocs/Publikationen/DE/Statistik/Fahrzeuge/FZ/2020_monatlich/FZ10/fz10_2020_03_xlsx.xlsx?__blob=publicationFile&v=2

In [64]:
df.head()

    Unnamed: 1_level_0                                            Insgesamt  \
                 Marke                               Modellreihe  März 2020
0           ALFA ROMEO                             ALFA GIULIETTA        27
1                  NaN                                     GIULIA        60
2                  NaN                                    STELVIO        64
3  ALFA ROMEO ZUSAMMEN                                        NaN       151
4               ALPINE                                       A110        20

                                 mit Dieselantrieb                   \
  Jan.-\nMärz 2020 Anteil \nin %         März 2020 Jan.-\nMärz 2020
0            153.0          23.2                 7               26
1            203.0          30.8                 3               21
2            304.0          46.1                17               92
3            660.0           0.1                27              139
4             50.0         100.0                 -                -

                mit Hybridantrieb                                 \
  Anteil \nin %         März 2020 Jan.-\nMärz 2020 Anteil \nin %
0          18.7                 -                -             -
1          15.1                 -                -             -
2          66.2                 -                -             -
3           0.1                 -                -             -
4             -                 -                -             -

  mit Elektroantrieb                                mit Allradantrieb  \
           März 2020 Jan.-\nMärz 2020 Anteil \nin %         März 2020
0                  -                -             -                 -
1                  -                -             -                13
2                  -                -             -                62
3                  -                -             -                75
4                  -                -             -                 -

                                 Cabriolets
  Jan.-\nMärz 2020 Anteil \nin %  März 2020 Jan.-\nMärz 2020 Anteil \nin %
0                -             -          -                -             -
1               98          26.2          -                -             -
2              276          73.8          -                -             -
3              374           0.2          -                -             -
4                -             -          -                -             -